version: '3.2'
#Environmental variables set in /etc/environment

volumes:
  portainer_data:
  ovpn_data:

networks:
  t1_proxy:
    external:
      name: t1_proxy
  default:
    driver: bridge

services:
  ddclient:
    image: linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERDIR}ddclient/config:/config
    restart: unless-stopped

  nodered:
    container_name: nodered
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - ${DOCKERDIR}nodered:/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      - TZ=${TZ}
    networks:
      - t1_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nodered"
      - "traefik.frontend.rule=Host:nodered.${DOMAINNAME}"  
      # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /nodered"
      - "traefik.port=1880"
      - "traefik.docker.network=t1_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      # - "traefik.frontend.headers.frameDeny: true" #customFrameOptionsValue overrides this
      - "traefik.frontend.headers.customFrameOptionsValue: allow-from https:${DOMAINNAME}"
      - "traefik.frontend.auth.basic.users=httpadmin:$$apr1$$ESjykpzJ$$itv3sKAATbfwo92DThEsc0"

  mqtt:
    container_name: mqtt
    image: toke/mosquitto
    volumes:
      - ${DOCKERDIR}mqtt/config:/mqtt/config:ro
      - ${DOCKERDIR}mqtt/log:/mqtt/log
      - ${DOCKERDIR}mqtt/data:/mqtt/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ports:
      - "1883:1883"
    environment:
      - TZ=${TZ}

  homeassistant:
    container_name: ha
    restart: always
    depends_on:
      - mqtt
    image: homeassistant/home-assistant
    devices:
      - /dev/ttyACM0
    volumes:
      - ${DOCKERDIR}hass:/config
      - /home/josh/.ssh:/.ssh
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8123:8123"
    privileged: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    network_mode: host
  
  
  portainer:
    container_name: portainer
    image: portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      - TZ=${TZ}
    networks:
      - t1_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:portainer.${DOMAINNAME}"  
#      - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /portainer"
      - "traefik.port=9000"
      - "traefik.docker.network=t1_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
#      - "traefik.frontend.headers.frameDeny: true" #customFrameOptionsValue overrides this
      - "traefik.frontend.headers.customFrameOptionsValue: allow-from https:${DOMAINNAME}"

  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ovpn_data:/etc/openvpn

  traefik:
    image: "traefik:v1.7.16"
    container_name: "traefik"
    restart: always
    domainname: ${DOMAINNAME}
    networks:
      - default
      - t1_proxy 
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"  
      # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /traefik"
      - "traefik.port=8080"
      - "traefik.docker.network=t1_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      # - "traefik.frontend.headers.frameDeny: true" #customFrameOptionsValue overrides this
      - "traefik.frontend.headers.customFrameOptionsValue: allow-from https:${DOMAINNAME}"
      - "traefik.frontend.auth.basic.users=httpadmin:$$apr1$$ESjykpzJ$$itv3sKAATbfwo92DThEsc0"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ${DOCKERDIR}traefik:/etc/traefik
      - ${DOCKERDIR}shared:/shared

  # grocy:
  #   image: linuxserver/grocy
  #   container_name: grocy
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Chicago
  #   volumes:
  #     - ${DOCKERDIR}grocy:/config
  #   ports:
  #     - "9283:80"
  #   restart: unless-stopped
