version: '3'
services:
  homeassistant:
    container_name: ha
    image: homeassistant/home-assistant
    volumes:
      - /docker/ha-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: host
