version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    volumes:
      - /srv/docker/ha-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: host
  mqtt:
    container_name: MQTT
    image: eclipse-mosquitto
    volumes:
      - /srv/docker/mosquitto/config:/mosquitto/config
      - /srv/docker/mosquitto/log:/mosquitto/log
      - /srv/docker/mosquitto/data:/mosquitto/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
  
