version: '3'
services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    volumes:
      - /opt/docker/mosquitto/config:/mosquitto/config:ro
      - /opt/docker/mosquitto/log:/mosquitto/log
      - /opt/docker/mosquitto/data/:/mosquitto/data/
    restart: on-failure
    ports:
      - "1883:1883"
